### ISSUE TITLE
gh repo create?

### ISSUE THREAD

**Issue by StoneCypher** [shunak/homework#1]
why would anyone use a third party tool to do this when there's already a first party tool for it?

[with gh cli](https://cli.github.com/manual/gh_repo_create)

[without gh cli](https://dev.to/bowmanjd/create-and-initialize-a-new-github-repository-from-the-command-line-85e)

**Comment by shunak** [comment]
"gh repo create" needs "git init" "git remote add origin https://github.com/username/some_repos.git
git branch -M main
git push -u origin main" isn't it ? I can't be bothered.
